# Generated by Django 2.1.3 on 2019-10-28 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=255)),
                ('edad', models.IntegerField()),
                ('telefono', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('animal', models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Erizo', 'Erizo'), ('Otro', 'Otro')], default='Erizo', max_length=20)),
                ('producto', models.CharField(choices=[('Collar', 'Collar'), ('Limpieza', 'Limpieza'), ('Ropa', 'Ropa')], default='Ropa', max_length=150)),
                ('precio', models.IntegerField(max_length=20)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Persona')),
            ],
        ),
    ]
